# Generated by Django 4.2.4 on 2023-10-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_recipe_recipeingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, default='https://www.thermaxglobal.com/wp-content/uploads/2020/05/image-not-found.jpg', max_length=500, null=True),
        ),
    ]
