# Generated by Django 4.2.4 on 2024-02-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'One Hat'), (2, 'Two Hats'), (3, 'Three Hats'), (4, 'Four Hats'), (5, 'Five Hats')], default=1, null=True),
        ),
    ]
