# Generated by Django 4.2.4 on 2024-02-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Appetizer', 'Appetizer'), ('Side', 'Side'), ('Other', 'Other')], default='Other', max_length=50, null=True),
        ),
    ]
